""" A program that prints  a (right-aligned)list of strings
Author: Afika Nyati
Date: 20th April 2014"""


def main():
    
    user_list = string_to_list() # Assigns the list generated by the string_to_list function to user_list variable
    
    print()
    
    longeststring = longest_string(user_list) # Assigns the integer that represents the longest of the strings in the list to the longeststring function.
    
    print_list_rightaligned(user_list, longeststring) # Inputs user_list and longeststring into the print_list_rightaligned function as parameters to print a formatted list of the strings.
    

def string_to_list():
    
    user_list = [] # Intializing a list
    
    entry = input("Enter strings (end with DONE):\n") # Asks user to enter a string
    
    while (entry != "DONE"): # A indefinite loop that continues to ask for a string, until the user types "DONE".
        user_list.append(entry) # This appends each string entry to the user_list list.
        entry = input("") # This asks the user for another string, and therefore carries on the loop. Input has nothing inside, so that the user can enter the strings one after the other.
        
    return user_list # Returns user_list


def longest_string(a_list):
    
    longest = 0 # Initializing longest variable
    
    for item in a_list:  # Creating a definite loop that goes through every item in the list parameter and finds the length of the longest string.
        
        length = len(item) # For each string, length varible becomes its length.
        
        if (length > longest): # If the current length is longer than longest, change longest to length.
            longest = length
            
    return longest # Return longest

def print_list_rightaligned(a_list, width):
    
    print("Right-aligned list:") # Prints a string
    
    for item in a_list: # For each item in the parameter list, print it with the given format.
        format_string = "{0:>" + str(width) + "}" # This format right-aligns each word accroding the the length of the longest string.
        print(format_string.format(item)) # Printing formatted strings
           
main()
