""" A program to count the number of votes for each political party in an election.
Author: Afika Nyati
Date: 21st April 2014"""

def main():
    
    print_intro() # Calls the print_intro function.
    votes, parties = enter_votes() # Assigns the two lists generated by the enter_votes function to two varibales.
    print_count(votes, parties) # Prints the votes each party receives in a nice format.
    

def print_intro():
    
    Heading = "Independent Electoral Commission"
    
    print(Heading) # Prints the relevant heading
    print("-" * (len(Heading))) # Underlines the heading based on the amount of characters in it.
    

def enter_votes():
    
    entry = input("Enter the names of parties (terminated by DONE):\n") # Asks the user to input a vote received by a party.
    
    votes_dict = {} # Initializes a dictionary that stores the number of votes each party receives.
    party_list = [] # Initializes a list that stores the names of all the parties that a part of the election.
    
    while (entry != "DONE"): # A indefinite loop that continues to ask to enter more votes until the user types "DONE".
        
        if (entry in party_list): # If the name of the party has already been accounted for (seen), increase its vote count in the vote_dict dictionary by one.
            votes_dict[entry] += 1
            
        else: # Else if the name of the party hasn't been accounted for (seen), add it to the party_list list and in the votes_dict dictionary with one vote.
            party_list.append(entry)
            votes_dict[entry] = 1
        
        entry = input("") # This asks the user for another vote, and therefore carries on the loop. Inout has nothing inside, so that the user can enter the strings one after the other.
    
    party_list.sort() # This sorts the list of parties in alphabetical order.
    print()
    
    return votes_dict, party_list # Returns the dictionary representing the votes each party received, and a list of all the parties represented in the election.


def print_count(vote_dict, party_list): # Takes in a dictionary representing the votes each party received, and a list of all the parties represented in the election as parameters.
    
    formatting = "{0:<10}" # This format string left-aligns the party names and places them in a width of 10 spaces.
    
    print("Vote counts:") # Prints a header
    
    for party in party_list: # A definite loop that prints out for each party in the party_list its name and the amount of votes it received.
        print(formatting.format(party), "-", vote_dict[party]) # Prints out the party name using the format and accesses the vote count from the parameter dictionary.


main()
    
    
            
        